[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qtblab"
version = "0.1"
readme = "README.md"
dependencies = [
   "numpy",
   "numba",
   "matplotlib",
]


[project.scripts]
